### ISSUE TITLE
Feature request: lap time and objects over classes

### ISSUE THREAD

**Issue by andig** [sebastianbergmann/php-timer#17]
I'd like to see the following features:
- support multiple timers by using objects instead of classes (maybe with a factory method)
- allow to wrap functionality in a timer without boilerplate code, something like:
  
  ``` php
  PHP_Timer::lap(function($timer) {
      // do stuff, may show intermediate timings
  })->then(function($timer) {
     echo $timer->timeAsString();
  });
  ```

**Comment by sebastianbergmann** [comment]
I am not interested in adding new features to this component.
