### ISSUE TITLE
 Class 'PHP_Timer' not found

### ISSUE THREAD

**Issue by jamesqjl** [sebastianbergmann/php-timer#20]
Today, I got the following error, and I Found that the Timer.php class is changed this morning.
The class name "PHP_Timer" is changed to "Timer".

01-Feb-2018 11:24:54	     [exec] **PHP Fatal error:  Uncaught Error: Class 'PHP_Timer' not found** in /bamboo/bamboo-home/xml-data/build-dir/196609/WEBS-WEB9-PUT/vendor/phpunit/phpunit/src/Framework/TestResult.php:577
01-Feb-2018 11:24:54	     [exec] Stack trace:
01-Feb-2018 11:24:54	     [exec] #0 /bamboo/bamboo-home/xml-data/build-dir/196609/WEBS-WEB9-PUT/vendor/phpunit/phpunit/src/Framework/TestCase.php(702): PHPUnit_Framework_TestResult->run(Object(BenefitTest))
01-Feb-2018 11:24:54	     [exec] #1 /bamboo/bamboo-home/xml-data/build-dir/196609/WEBS-WEB9-PUT/vendor/phpunit/phpunit/src/Framework/TestSuite.php(735): PHPUnit_Framework_TestCase->run(Object(PHPUnit_Framework_TestResult))
01-Feb-2018 11:24:54	     [exec] #2 /bamboo/bamboo-home/xml-data/build-dir/196609/WEBS-WEB9-PUT/vendor/phpunit/phpunit/src/Framework/TestSuite.php(735): PHPUnit_Framework_TestSuite->run(Object(PHPUnit_Framework_TestResult))
01-Feb-2018 11:24:54	     [exec] #3 /bamboo/bamboo-home/xml-data/build-dir/196609/WEBS-WEB9-PUT/vendor/phpunit/phpunit/src/TextUI/TestRunner.php(432): PHPUnit_Framework_TestSuite->run(Object(PHPUnit_Framework_TestResult))
01-Feb-2018 11:24:54	     [exec] #4 /bamboo/bamboo-home/xml-data/build-dir/196609/WEBS-WEB9-PUT/vendor/phpunit/phpunit/src/TextUI/Command in /bamboo/bamboo-home/xml-data/build-dir/196609/WEBS-WEB9-PUT/vendor/phpunit/phpunit/src/Framework/TestResult.php on line 577

**Comment by jamesqjl** [comment]
How can I fix it?

**Comment by jamesqjl** [comment]
Currently I use phpunit-4.8.9

**Comment by sebastianbergmann** [comment]
How can you possibly get the new version with PHPUnit 4.8?

**Comment by sebastianbergmann** [comment]
```
$ composer require --dev phpunit/phpunit ^4.8
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 21 installs, 0 updates, 0 removals
  - Installing symfony/yaml (v3.4.4): Loading from cache
  - Installing sebastian/version (1.0.6): Loading from cache
  - Installing sebastian/global-state (1.1.1): Loading from cache
  - Installing sebastian/recursion-context (1.0.5): Loading from cache
  - Installing sebastian/exporter (1.2.2): Loading from cache
  - Installing sebastian/environment (1.3.8): Loading from cache
  - Installing sebastian/diff (1.4.3): Loading from cache
  - Installing sebastian/comparator (1.2.4): Loading from cache
  - Installing doctrine/instantiator (1.1.0): Loading from cache
  - Installing phpunit/php-text-template (1.2.1): Loading from cache
  - Installing phpunit/phpunit-mock-objects (2.3.8): Loading from cache
  - Installing phpunit/php-timer (1.0.9): Loading from cache
  - Installing phpunit/php-file-iterator (1.4.5): Loading from cache
  - Installing phpunit/php-token-stream (1.4.12): Loading from cache
  - Installing phpunit/php-code-coverage (2.2.4): Loading from cache
  - Installing webmozart/assert (1.3.0): Loading from cache
  - Installing phpdocumentor/reflection-common (1.0.1): Loading from cache
  - Installing phpdocumentor/type-resolver (0.4.0): Loading from cache
  - Installing phpdocumentor/reflection-docblock (4.3.0): Loading from cache
  - Installing phpspec/prophecy (1.7.3): Loading from cache
  - Installing phpunit/phpunit (4.8.36): Loading from cache
symfony/yaml suggests installing symfony/console (For validating YAML files using the lint command)
sebastian/global-state suggests installing ext-uopz (*)
phpunit/phpunit-mock-objects suggests installing ext-soap (*)
phpunit/phpunit suggests installing phpunit/php-invoker (~1.1)
Writing lock file
Generating autoload files
```

**Comment by jamesqjl** [comment]
I configure the following version in the composer.json.
"phpunit/phpunit" : "4.8.9",
but it installed php_timer 2.0.0 instead of 1.0.9

**Comment by jamesqjl** [comment]
It works after I changed the version in  composer.json  from "4.8.9" to ^4.8 !
sebastianbergmann, thank you very much!

**Comment by nelson1995** [comment]
i configured phpunit to use latest version in composer.json
` {
    "require-dev": {
        "phpunit/phpunit": "5.6.3"
    }`
Then I typed  `composer update`  on command prompt. After that, it worked.
