### ISSUE TITLE
Installation failed - Requirements could not be resolved

### ISSUE THREAD

**Issue by eleftrik** [sebastianbergmann/php-timer#29]
I know this isn't a specific problem of this package, but I kindly ask for your help.

I've a Laravel 7 project with this composer.json:

`
    "require-dev": {
        ...
        "phpunit/phpunit": "^8.5"
    },
    ...
    "minimum-stability": "dev",
    "prefer-stable": true,
`

When I run `composer require phpunit/php-timer`, I got this error:

> Using version ^3.0 for phpunit/php-timer
> ./composer.json has been updated
> Loading composer repositories with package information
> Updating dependencies (including require-dev)
> Your requirements could not be resolved to an installable set of packages.
> 
>   Problem 1
>     - phpunit/phpunit 8.5.2 requires phpunit/php-timer ^2.1.2 -> satisfiable by phpunit/php-timer[2.1.2] but these conflict with your requirements or minimum-stability.
>     - phpunit/phpunit 8.5.2 requires phpunit/php-timer ^2.1.2 -> satisfiable by phpunit/php-timer[2.1.2] but these conflict with your requirements or minimum-stability.
>     - phpunit/phpunit 8.5.2 requires phpunit/php-timer ^2.1.2 -> satisfiable by phpunit/php-timer[2.1.2] but these conflict with your requirements or minimum-stability.
>     - Installation request for phpunit/phpunit (locked at 8.5.2, required as ^8.5) -> satisfiable by phpunit/phpunit[8.5.2].
> 

What can I do to install this package?

Thank you very much for any help.

**Comment by sebastianbergmann** [comment]
This is not a discussion or support forum, sorry.

**Comment by eleftrik** [comment]
Sorry @sebastianbergmann, you're absolutely right.

By the way, I had only to better read the error.
Solved running `composer require phpunit/php-timer "^2.1.2"`
