### ISSUE TITLE
Add a TimerInterface so external packages can mock or spy the timer

### ISSUE THREAD

**Issue by robiningelbrecht** [sebastianbergmann/php-timer#41]
Currently the `Timer` class is `final`, which means it cannot be mocked or extended and that's ok for general usage.
But because of this external packages cannot properly test any classes using the this timer.
Introducing an interface for the timer would fix this problem... or am I missing something?

**Comment by sebastianbergmann** [comment]
This is outside the scope of this project (as I do not have any use case where I need to isolate `Timer` from code that uses it for testing).
